### ISSUE TITLE
impossible to start

### ISSUE THREAD

**Issue by HashersClub** [bigsky77/twitter-agent#6]
Hi @bigsky77 , 

I am trying to make this software works. 
I followed the installation and execution process but it doesn't work in the end. 

**First problem :** 
When i first run `python src/main.py --run-engine`, i encounter this error : 

`Error in run: Query was not successful! Unexpected status code: 422, with response body: {'error': [{'message': 'no graphql provider present, this is most likely because no schema is present. Import a schema first!'}]}.`

Problem seems to be solved by running weaviate_schema.py. 

**Second problem:** 

When i rerun `python src/main.py --run-engine` , i have this new error : 

`Error in run: 'data'`

When i try to run `python src/main.py --ingest `, it returns : 

```
/home/X/twitter-agent/venv/lib/python3.10/site-packages/tweepy/auth.py:120: DeprecationWarning: OAuthHandler is deprecated; use OAuth1UserHandler instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/X/twitter-agent/src/main.py", line 130, in <module>
    asyncio.run(main())
  File "/home/X/twitter-agent/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/X/twitter-agent/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/X/twitter-agent/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/X/twitter-agent/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/X/twitter-agent/src/main.py", line 33, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/X/twitter-agent/src/main.py", line 78, in main
    await collector.ingest()
  File "/home/X/twitter-agent/src/collector/collector.py", line 25, in ingest
    return await self.ingest_weighted_lists(50)
  File "/home/X/twitter-agent/src/collector/collector.py", line 76, in ingest_weighted_lists
    for list_data in lists:
TypeError: 'NoneType' object is not iterable
```

Thank you for your work. 

Cheers

**Comment by bigsky77** [comment]
Hey!  Thanks for checking out.  Twitter recently made some breaking changes to their API, so some of the methods used by these bots no longer work.  

If I get some time this weekend I'll dive in and try and fix.

**Comment by shubhamofbce** [comment]
@bigsky77 Twitter API is also paid now, Is this right ??
Does that mean we can not start this app without having a paid twitter api subscription ??

**Comment by shubhamofbce** [comment]
I got my answer, they give free developer account as well but according to readme that will not work with timelines.
I am interested in contributing to this project. Can we connect on twitter https://twitter.com/Shubham_hin or any other medium how we can connect.
